create table <?= DB_SCHEMA ?>.matrix_milestones (
	_id int not null auto_increment comment 'Identificador',
	_name Varchar(64) not null comment 'Nombre',
	_description Varchar(1024) null comment 'Descripción',
	_goal int not null comment 'Objetivo',
	primary key (_id),
	unique key uk_milestones_goals_name (_goal, _name),
	foreign key (_goal) references <?= DB_SCHEMA ?>.matrix_goals(_id)
)
engine = InnoDB
comment = 'Hitos o resultados';

insert into <?= DB_SCHEMA ?>.matrix_milestones (_id, _name, _description, _goal) values
(1, 'Desarrollo de competencias', 'Se comprende la competencia como la unión de las habilidades, los conocimientos, las aptitudes y los valores para la resolución de problemas. Se comprende una competencia como la capacidad de aplicar los conocimientos, junto con las destrezas y habilidades, para desempeñar una actividad profesional, de manera satisfactoria y en un contexto determinado.', 1),
(2, 'Robustecimiento de la calidad pedagógica', 'Brindar recursos y materiales didácticos en diferentes formatos como apoyo al proceso de enseñanza y aprendizaje.', 1),
(3, 'Evaluación Estandarizada digital para calidad educativa', 'La evaluación de los aprendizajes, es un proceso continuo de recopilación de información cualitativa y cuantitativa, que fundamenta la emisión de juicios de valor y la toma de decisiones por parte de la persona docente y el estudiantado, para la mejora progresiva de los procesos de enseñanza y aprendizaje.', 1),
(4, 'Evaluación de los aprendizajes del aula', 'Para desarrollar estrategias de recuperación de los aprendizajes en el aula y verificar el avance en el desempeño a estudiantes, docentes a nivel nacional aplicarán una prueba comprensiva para orientar la Recuperación de los Aprendizajes o Figuras Afines al inicio, se aplicarán al inicio del curso lectivo, a partir del 27 de febrero y la segunda, a partir del 31 de julio. a docentes deben realizar un diagnóstico donde se corrobore el nivel de preparación a estudiantes, conforme al Reglamento de Evaluación de los Aprendizajes recientemente aprobado por el CSE (AC-CSE-19-03-2023), que establece que las funciones de la evaluación de los aprendizajes permite conocer el estado inicial del estudiante en las áreas del desarrollo: cognoscitiva, socio afectiva y psicomotriz; con base en la información obtenida, permite la aplicación de estrategias para la recuperación de aprendizajes.', 1),
(5, 'Desarrollo de aceleradores para la recuperación', 'Las personas estudiantes contarán con una Mochila Digital (en línea y fuera de línea) que contiene recursos didácticos para fortalecer y recuperar los aprendizajes. Esta se encontrará disponible a partir del segundo semestre 2023 y se continuará complementando y actualizando a lo largo de los años lectivos. Todos a docentes contarán con la Caja de Herramientas, que contiene recursos didácticos actualizados y atractivos para mejorar el proceso de enseñanza, también a mediados del 2023. Se promueve el uso de aceleradores que incluye juegos, actividades y dinámicas que le ponen color, motivación, interactividad y alegría al aprendizaje.\r\nAlgunos de los aceleradores que ya están producidos son:\r\n* Programa STEAM\r\n* Aprendo Pura Vida\r\n* Plataforma Nacional Educativa\r\n* Programa Nacional Leyendo y Contando producido en alianza con Microsoft C.R\r\n* ABC Mouse\r\n* My Math Academy', 1),
(6, 'Educación de primera infancia', 'Apoyo educativo que brindarla a los centros de cuido y desarrollo infantil a partir de la reforma de la Ley de Red Nacional de Cuido y Desarrollo Infantil liderada por la Segunda Vicepresidencia de la República que coordina el sector social.', 1),
(7, 'Fortalecimiento de la educación indígena', 'Implementar estrategias de mejora de la calidad del servicio educativo indígena.', 1),
(8, 'Universalización de la conectividad', 'Proporcionar servicio de conectividad adecuado a los Centros Educativos.', 2),
(9, 'Mejora del servicio de comedores para estudiantes', '* Ampliar la cobertura del servicio de alimentación, garantizando al menos un tiempo adicional de comida, principalmente de desayuno, a estudiantes de Centros Educativos que presenten condiciones desfavorables ubicados en zonas con IDS bajo y muy bajo.\r\n* Menú indígena implementado en los 24 territorios.\r\n* Nuevo reglamento del Programa de Alimentación y Nutrición implementado.\r\n* Universalización del Programa de comedores estudiantiles en el 100% de Centros Educativos de preescolar y primaria.', 2),
(10, 'Más estudiantes en pobreza o condición de discapacidad contarán ', '* 100% de estudiantes en condición de discapacidad y pobreza de Centros Educativos de Enseñanza Especial; y un incremento del 5% de inversión del programa para casos particulares en Centros Educativos regulares, ubicados en zonas de Índice de Desarrollo Social (IDS) bajo y muy bajo\r\n* Acceso al servicio de transporte para estudiantes en riesgo y vulnerabilidad.\r\n* Migración del modelo administrado por las Juntas de Educación y Administrativas a un modelo institucional regionalizado de rutas adjudicadas mediante SICOP, estableciendo un nuevo modelo de contratación de rutas para gestionar de forma centralizada la adquisición, fiscalización y administración de contratos del servicio de transporte estudiantil.', 2),
(11, 'Rescate y renovación de infraestructura educativa', 'Fortalecimiento y adecuación de la infraestructura educativa.', 2),
(12, 'Contención de órdenes sanitarias', 'Mantenimiento preventivo de la infraestructura educativa para minimizar la interposición de órdenes sanitarias.', 2),
(13, 'Gerenciamiento integral de recursos humanos', 'Establecer el perfil deseado del docente idóneo y durante los años siguientes, actualizando el perfil deseado en un proceso participativo (insumos requeridos para la prueba de idoneidad y para el nuevo modelo de evaluación del desempeño).\r\nA docentes determinarán su perfil real y el plan de cierre de la brecha, para lo cual contarán con el apoyo de cursos virtuales auto gestionados.\r\nIncluye una herramienta informática para capacitar a docentes en línea en las diferentes temáticas del MEP. Se medirá el impacto del proyecto, se elaborarán y difundirán los manuales para el uso de la herramienta, y realizarán sesiones trabajo con los actores internos, a fin de probar y avalar la herramienta.\r\nTambién se establecerá un nuevo modelo de pruebas de idoneidad, definiendo una comisión institucional y multidisciplinaria para facilitar las acciones tendentes a su implementación.', 2),
(14, 'Articulación interinstitucional', 'Coordinación interinstitucional que fortalezca el trabajo conjunto con instancias del Estado y Gobiernos Locales para la prevención y atención de incidencias en los Centros Educativos.', 3),
(15, 'Financiamiento flexible a estudiantes de secundaria y docentes', 'Incentivar las capacidades lingüísticas a estudiantes y docentes mediante apoyos no reembolsables y préstamos blandos.', 3),
(16, 'Reorganización y desconcentración institucional', 'Rediseño organizativo del MEP en conjunto con MIDEPLAN.', 3),
(17, 'Nuevos controles, sistemas y automatización', 'Mejoramiento de sistema de control para toma de decisiones.', 3);

