create table <?= DB_SCHEMA ?>.security_groups (
	_id int not null auto_increment,
	_name varchar(64) not null,
	primary key (_id),
	unique key uk_groups_name(_name)
)
engine = InnoDB
comment = '';

insert into <?= DB_SCHEMA ?>.security_groups (_id, _name) values
(1, 'DDC'),
(2, 'DRE'),
(3, 'DGDR'),
(4, 'DETCE'),
(5, 'IDPUGS'),
(6, 'DVE'),
(7, 'Despacho Académico'),
(8, 'DGEC'),
(9, 'DRTE'),
(10, 'DIG'),
(11, 'DEP'),
(12, 'DPI'),
(13, 'CROE'),
(14, 'Despacho Ministerial'),
(15, 'DPRP'),
(16, 'DIE'),
(17, 'DPE'),
(18, 'PI'),
(19, 'DAJ'),
(20, 'Fideicomiso'),
(21, 'DRH'),
(22, 'Comisión Nombre'),
(23, 'Despacho Administrativo'),
(24, 'DAIC'),
(25, 'CDE'),
(26, 'UPRE'),
(27, 'Despacho Planificación'),
(28, 'Coordinadores PP'),
(29, 'CONESUP'),
(30, 'Viceministerio Administrativo'),
(31, 'DRE & DGDR & DDC'),
(32, 'DDC & DETCE'),
(33, 'DDC & DVE & DRE'),
(34, 'DDC & DRE'),
(35, 'DGEC & DRTE'),
(36, 'DRE & DIG'),
(37, 'DIG & DGEC'),
(38, 'DDC & DIG & DEP'),
(39, 'DDC & DIG'),
(40, 'DDC & DRE & DPI'),
(41, 'DDC & DEP & CROE'),
(42, 'DDC & DEP & DRE'),
(43, 'DDC & Despacho Ministerial'),
(44, 'Despacho Ministerial & DPRP'),
(45, 'Despacho Ministerial & DVE'),
(46, 'DIG & DRTE'),
(47, 'DIG & DRTE & DIE'),
(48, 'DPE (Subsistema de Educación Indígena)'),
(49, 'DPE & PI & DRE'),
(50, 'DIE & DAJ & Fideicomiso'),
(51, 'DIE & DRE'),
(52, 'DRH & Comisión Nombre'),
(53, 'DRH & Despacho Académico & Despacho Administrativo'),
(54, 'Despacho Académico & Despacho Administrativo & DRH'),
(55, 'DRH & Despacho Administrativo'),
(56, 'Despacho Ministerial & DVE & DAIC & CDE'),
(57, 'DGDR & DVE'),
(58, 'DPRP & Despacho Planificación'),
(59, 'DDC & DVE & DAJ & CDE & DRH & UPRE & DRE & DETCE'),
(60, 'DPI & DRH & Coordinadores PP'),
(61, 'DIE & Fideicomiso & Despacho ministerial'),
(62, 'Despacho de Planificación & DPI'),
(63, 'UPRE & Viceministerio Administrativo & DIG');

